"use client";
import {FormEvent,useEffect,useState} from "react";
import DashboardShell from "@/components/DashboardShell";
import {ADMIN_NAV} from "@/lib/dashboard-nav";
import {authedNalarva,formatDate} from "@/lib/apps-script";
import {Empty,Loading,Message,PageHead,Panel,Status} from "@/components/dashboard/DashboardUI";
type Row=Record<string,any>;
export default function Page(){
 const [rows,setRows]=useState<Row[]>([]),[classes,setClasses]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(){setLoading(true);const [a,b]=await Promise.all([authedNalarva<Row[]>("adminListStudents"),authedNalarva<Row[]>("listClasses")]);setRows(a.data||[]);setClasses(b.data||[]);setLoading(false)}useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setMsg("");const r=await authedNalarva<Row>("adminCreateStudent",Object.fromEntries(new FormData(form).entries()));setBusy(false);setMsg(r.message||"");if(r.ok){form.reset();await load()}}
 async function resetPassword(id:string){if(!window.confirm("Buat password sementara baru untuk siswa ini? Semua sesi siswa akan dikeluarkan."))return;const r=await authedNalarva<Row>("adminResetUserPassword",{userId:id});setMsg(r.message||"")}
 async function toggle(r:Row){const next=String(r.status)==="ACTIVE"?"SUSPENDED":"ACTIVE";if(!window.confirm(`${next==="ACTIVE"?"Aktifkan":"Nonaktifkan"} akun ${r.name}?`))return;const x=await authedNalarva("adminUpdateUserStatus",{userId:r.id,status:next});setMsg(x.message||"");if(x.ok)await load()}
 return <DashboardShell accessRole="ADMIN" role="Administrator" name="Admin Nalarva" initials="AD" nav={ADMIN_NAV}><PageHead eyebrow="Manajemen Siswa" title="Siswa Nalarva" desc="Buat akun, atur akses, reset password, dan tempatkan siswa ke kelas."/><div className="ops-grid"><Panel eyebrow="AKUN BARU" title="Tambah siswa"><form className="dash-form" onSubmit={submit}><label>Nama lengkap<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><div className="form-two"><label>Jenjang<select name="level"><option>SMA</option><option>SMP</option><option>SD</option></select></label><label>Sekolah<input name="school"/></label></div><div className="form-two"><label>Nama orang tua<input name="parentName"/></label><label>WhatsApp orang tua<input name="parentPhone"/></label></div><label>Masukkan ke kelas<select name="classId"><option value="">Belum ditentukan</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} ({c.enrolled_count||0}/{c.capacity})</option>)}</select></label><button className="btn primary wide" disabled={busy}>{busy?"Membuat akun...":"Buat akun siswa"}</button>{msg&&<Message text={msg}/>}</form></Panel><Panel eyebrow="DATABASE" title={`Daftar siswa (${rows.length})`}>{loading?<Loading/>:rows.length===0?<Empty text="Belum ada akun siswa."/>:<div className="table-wrap"><table><thead><tr><th>Siswa</th><th>Jenjang</th><th>Sekolah</th><th>Status</th><th>Bergabung</th><th>Aksi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b><br/><small>{r.email}</small></td><td>{r.level||"—"}</td><td>{r.school||"—"}</td><td><Status value={r.status}/></td><td>{formatDate(r.joined_at)}</td><td><div className="table-actions"><button onClick={()=>void resetPassword(r.id)}>Reset password</button><button onClick={()=>void toggle(r)}>{String(r.status)==="ACTIVE"?"Nonaktifkan":"Aktifkan"}</button></div></td></tr>)}</tbody></table></div>}</Panel></div></DashboardShell>
}
