"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import DashboardShell from "@/components/DashboardShell";
import {STUDENT_NAV} from "@/lib/dashboard-nav";
import {authedNalarva,formatDate} from "@/lib/apps-script";
import {Empty,Message,PageHead,Panel,Status} from "@/components/dashboard/DashboardUI";
type Row=Record<string,any>;type Started={attemptId:string;exam:Row;questions:Row[];startedAt?:string;expiresAt?:string};
function clock(sec:number){const s=Math.max(0,sec),m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,"0")}:${String(r).padStart(2,"0")}`}
export default function Page(){
 const [exams,setExams]=useState<Row[]>([]),[started,setStarted]=useState<Started|null>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[flagged,setFlagged]=useState<Record<string,boolean>>({}),[current,setCurrent]=useState(0),[result,setResult]=useState<Row|null>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[seconds,setSeconds]=useState(0),[showReview,setShowReview]=useState(false);const autoSubmitting=useRef(false);
 useEffect(()=>{authedNalarva<Row[]>("listExams").then(r=>setExams(r.data||[]))},[]);
 const answered=useMemo(()=>Object.keys(answers).filter(k=>answers[k]).length,[answers]);const unanswered=started?started.questions.length-answered:0;
 async function start(id:string){setBusy(true);setMsg("");const r=await authedNalarva<Started>("startExam",{examId:id});setBusy(false);if(r.ok&&r.data){const data=r.data;setStarted(data);setResult(null);const key=`nalarva:attempt:${data.attemptId}`;try{const saved=JSON.parse(localStorage.getItem(key)||"{}");setAnswers(saved.answers||{});setFlagged(saved.flagged||{});setCurrent(Math.min(Number(saved.current)||0,Math.max(0,data.questions.length-1)))}catch{setAnswers({});setFlagged({});setCurrent(0)}const end=data.expiresAt?new Date(data.expiresAt).getTime():Date.now()+Number(data.exam.duration_minutes||60)*60000;setSeconds(Math.max(0,Math.ceil((end-Date.now())/1000)))}else setMsg(r.message||"Tryout tidak dapat dimulai.")}
 useEffect(()=>{if(!started)return;const key=`nalarva:attempt:${started.attemptId}`;localStorage.setItem(key,JSON.stringify({answers,flagged,current}));},[answers,flagged,current,started]);
 useEffect(()=>{if(!started||result)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault()};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[started,result]);
 useEffect(()=>{if(!started||result)return;const t=window.setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>window.clearInterval(t)},[started,result]);
 useEffect(()=>{if(started&&!result&&seconds===0&&!autoSubmitting.current){autoSubmitting.current=true;void submit(true)}},[seconds,started,result]);
 async function submit(auto=false){if(!started||busy)return;if(!auto&&!window.confirm(unanswered?`Masih ada ${unanswered} soal belum dijawab. Tetap kirim tryout?`:"Kirim jawaban tryout sekarang?"))return;setBusy(true);const payload=Object.entries(answers).map(([questionId,answer])=>({questionId,answer}));const r=await authedNalarva<Row>("submitExam",{attemptId:started.attemptId,answers:payload});setBusy(false);if(r.ok&&r.data){localStorage.removeItem(`nalarva:attempt:${started.attemptId}`);setResult(r.data);setMsg(auto?"Waktu habis. Jawaban otomatis dikirim.":r.message||"Tryout selesai.")}else{autoSubmitting.current=false;setMsg(r.message||"Tryout gagal dikirim.")}}
 if(started&&!result){const q=started.questions[current];return <DashboardShell accessRole="SISWA" role="Siswa · TKA" name="Siswa Nalarva" initials="SN" nav={STUDENT_NAV}><PageHead eyebrow="Tryout Berlangsung" title={started.exam.title} desc={`${started.questions.length} soal · jawaban tersimpan otomatis di perangkat ini`}/><div className="pro-exam"><main className="pro-question"><div className="question-toolbar"><span>Soal {current+1} dari {started.questions.length}</span><button className={flagged[q.id]?"flag active":"flag"} onClick={()=>setFlagged(f=>({...f,[q.id]:!f[q.id]}))}>{flagged[q.id]?"★ Ditandai":"☆ Tandai ragu-ragu"}</button></div><h2>{q.question_text}</h2><div className="pro-options">{["A","B","C","D","E"].filter(x=>q[`option_${x.toLowerCase()}`]||q[`option_${x.toLowerCase()}`]===0).map(x=>{const key=`option_${x.toLowerCase()}`;return <label className={answers[q.id]===x?"selected":""} key={x}><input type="radio" name={q.id} checked={answers[q.id]===x} onChange={()=>setAnswers(a=>({...a,[q.id]:x}))}/><b>{x}</b><span>{q[key]}</span></label>})}</div><div className="question-actions"><button className="btn ghost" disabled={current===0} onClick={()=>setCurrent(i=>Math.max(0,i-1))}>← Sebelumnya</button><button className="btn primary" disabled={current===started.questions.length-1} onClick={()=>setCurrent(i=>Math.min(started.questions.length-1,i+1))}>Berikutnya →</button></div></main><aside className="pro-exam-side"><div className={seconds<300?"exam-timer danger":"exam-timer"}><span>Sisa waktu</span><b>{clock(seconds)}</b></div><div className="exam-summary"><span><i className="dot answered"/>Terjawab <b>{answered}</b></span><span><i className="dot flagged"/>Ditandai <b>{Object.values(flagged).filter(Boolean).length}</b></span><span><i className="dot blank"/>Belum <b>{unanswered}</b></span></div><div className="question-nav">{started.questions.map((x,i)=><button key={x.id} className={`${i===current?"current ":""}${answers[x.id]?"answered ":""}${flagged[x.id]?"flagged":""}`} onClick={()=>setCurrent(i)}>{i+1}</button>)}</div><button className="btn primary wide" disabled={busy} onClick={()=>void submit(false)}>{busy?"Mengirim...":"Selesai & kirim"}</button>{msg&&<Message text={msg}/>}</aside></div></DashboardShell>}
 if(result)return <DashboardShell accessRole="SISWA" role="Siswa · TKA" name="Siswa Nalarva" initials="SN" nav={STUDENT_NAV}><PageHead eyebrow="Hasil Tryout" title="Tryout selesai" desc="Nilai sudah dihitung dan tersimpan di akunmu."/><div className="result-hero"><span>Skor kamu</span><b>{result.score}</b><p>{result.correctCount} benar · {result.wrongCount} salah · Rank #{result.rank||"—"} · Percentile {result.percentile||"—"}</p><div className="result-actions"><button className="btn white" onClick={()=>setShowReview(v=>!v)}>{showReview?"Tutup pembahasan":"Lihat pembahasan"}</button><a className="btn gold" href="/dashboard/siswa/analisis">Lihat analisis</a></div></div>{msg&&<Message text={msg}/>} {showReview&&Array.isArray(result.review)&&<Panel eyebrow="PEMBAHASAN" title="Review jawaban"><div className="review-list">{result.review.map((r:any,i:number)=><article className={r.isCorrect?"correct":"wrong"} key={r.questionId}><div><b>Soal {i+1}</b><Status value={r.isCorrect?"BENAR":"SALAH"}/></div><h3>{r.questionText}</h3><p>Jawaban kamu: <strong>{r.answer||"Tidak dijawab"}</strong> · Kunci: <strong>{r.correctAnswer}</strong></p>{r.explanation&&<small>{r.explanation}</small>}</article>)}</div></Panel>}</DashboardShell>;
 return <DashboardShell accessRole="SISWA" role="Siswa · TKA" name="Siswa Nalarva" initials="SN" nav={STUDENT_NAV}><PageHead eyebrow="Tryout" title="Simulasi TKA" desc="Timer dimulai saat tryout dibuka. Jawaban tersimpan otomatis di browser selama pengerjaan."/><div className="card-grid">{exams.map(e=><article className="class-card" key={e.id}><div className="class-card-top"><span>{e.program_name||"TKA"}</span><Status value={e.status}/></div><h3>{e.title}</h3><p>{e.question_count||0} soal · {e.duration_minutes} menit</p><div className="class-meta"><span>Mulai <b>{formatDate(e.start_at)}</b></span><span>Sampai <b>{formatDate(e.end_at)}</b></span></div><button className="btn primary wide" disabled={busy||String(e.status)!=="PUBLISHED"} onClick={()=>void start(e.id)}>Mulai tryout</button></article>)}</div>{exams.length===0&&<Panel title="Belum ada tryout"><Empty/></Panel>}{msg&&<Message text={msg}/>}</DashboardShell>
}
