"use client";
import {FormEvent,useEffect,useState} from "react";
import DashboardShell from "@/components/DashboardShell";
import {ADMIN_NAV} from "@/lib/dashboard-nav";
import {authedNalarva,formatDate} from "@/lib/apps-script";
import {Empty,Loading,Message,PageHead,Panel,Status} from "@/components/dashboard/DashboardUI";
type Row=Record<string,any>;
export default function Page(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");async function load(){setLoading(true);const r=await authedNalarva<Row[]>("adminListTutors");setRows(r.data||[]);setLoading(false)}useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);const r=await authedNalarva<Row>("adminCreateTutor",Object.fromEntries(new FormData(form).entries()));setBusy(false);setMsg(r.message||"");if(r.ok){form.reset();await load()}}
 async function resetPassword(id:string){if(!window.confirm("Buat password sementara baru untuk tutor ini? Semua sesi tutor akan dikeluarkan."))return;const r=await authedNalarva<Row>("adminResetUserPassword",{userId:id});setMsg(r.message||"")}
 async function toggle(r:Row){const next=String(r.status)==="ACTIVE"?"SUSPENDED":"ACTIVE";if(!window.confirm(`${next==="ACTIVE"?"Aktifkan":"Nonaktifkan"} akun ${r.name}?`))return;const x=await authedNalarva("adminUpdateUserStatus",{userId:r.id,status:next});setMsg(x.message||"");if(x.ok)await load()}
 return <DashboardShell accessRole="ADMIN" role="Administrator" name="Admin Nalarva" initials="AD" nav={ADMIN_NAV}><PageHead eyebrow="Manajemen Tutor" title="Tutor Nalarva" desc="Buat akun tutor, atur akses, dan reset password bila dibutuhkan."/><div className="ops-grid"><Panel eyebrow="AKUN BARU" title="Tambah tutor"><form className="dash-form" onSubmit={submit}><label>Nama lengkap<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Spesialisasi<input name="specialization" placeholder="Contoh: Matematika & Numerasi" required/></label><label>Nomor WhatsApp<input name="phone"/></label><button className="btn primary wide" disabled={busy}>{busy?"Membuat...":"Buat akun tutor"}</button>{msg&&<Message text={msg}/>}</form></Panel><Panel eyebrow="DATABASE" title={`Daftar tutor (${rows.length})`}>{loading?<Loading/>:rows.length===0?<Empty text="Belum ada tutor."/>:<div className="table-wrap"><table><thead><tr><th>Tutor</th><th>Spesialisasi</th><th>WhatsApp</th><th>Status</th><th>Bergabung</th><th>Aksi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b><br/><small>{r.email}</small></td><td>{r.specialization||"—"}</td><td>{r.phone||"—"}</td><td><Status value={r.status}/></td><td>{formatDate(r.joined_at)}</td><td><div className="table-actions"><button onClick={()=>void resetPassword(r.id)}>Reset password</button><button onClick={()=>void toggle(r)}>{String(r.status)==="ACTIVE"?"Nonaktifkan":"Aktifkan"}</button></div></td></tr>)}</tbody></table></div>}</Panel></div></DashboardShell>
}
