"use client";
import {FormEvent,useEffect,useState} from "react";
import DashboardShell from "@/components/DashboardShell";
import {ADMIN_NAV} from "@/lib/dashboard-nav";
import {authedNalarva} from "@/lib/apps-script";
import {Empty,Message,PageHead,Panel,Status} from "@/components/dashboard/DashboardUI";
type Row=Record<string,any>;
export default function Page(){
 const [qs,setQs]=useState<Row[]>([]),[programs,setPrograms]=useState<Row[]>([]),[exams,setExams]=useState<Row[]>([]),[items,setItems]=useState<Row[]>([]),[examId,setExamId]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const [a,b,c]=await Promise.all([authedNalarva<Row[]>("listQuestions"),authedNalarva<Row[]>("listPrograms"),authedNalarva<Row[]>("listExams")]);setQs(a.data||[]);setPrograms(b.data||[]);setExams(c.data||[])}useEffect(()=>{void load()},[]);async function loadItems(id:string){setExamId(id);if(!id){setItems([]);return}const r=await authedNalarva<Row[]>("listExamItems",{examId:id});setItems(r.data||[])}
 async function createQ(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);const r=await authedNalarva("adminCreateQuestion",Object.fromEntries(new FormData(form).entries()));setBusy(false);setMsg(r.message||"");if(r.ok){form.reset();await load()}}
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);const payload=Object.fromEntries(new FormData(form).entries());const r=await authedNalarva("adminAddQuestionToExam",payload);setBusy(false);setMsg(r.message||"");if(r.ok){await load();const id=String(payload.examId||"");if(id)await loadItems(id)}}
 async function remove(id:string){if(!window.confirm("Keluarkan soal ini dari tryout? Soal tetap tersimpan di Bank Soal."))return;const r=await authedNalarva("adminRemoveQuestionFromExam",{examItemId:id});setMsg(r.message||"");if(r.ok&&examId)await loadItems(examId)}
 return <DashboardShell accessRole="ADMIN" role="Administrator" name="Admin Nalarva" initials="AD" nav={ADMIN_NAV}><PageHead eyebrow="Assessment" title="Bank soal" desc="Simpan soal pilihan ganda, hubungkan ke tryout, dan cek susunan soal."/>{msg&&<Message text={msg}/>}<div className="ops-grid"><Panel eyebrow="SOAL BARU" title="Tambah soal"><form className="dash-form" onSubmit={createQ}><label>Program<select name="programId" required>{programs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="form-two"><label>Mata pelajaran<input name="subject" required/></label><label>Topik<input name="topic" required/></label></div><label>Pertanyaan<textarea name="questionText" required/></label>{["A","B","C","D","E"].map(x=><label key={x}>Pilihan {x}<input name={`option${x}`} required={x!=="E"}/></label>)}<div className="form-two"><label>Jawaban benar<select name="correctAnswer"><option>A</option><option>B</option><option>C</option><option>D</option><option>E</option></select></label><label>Kesulitan<select name="difficulty"><option>MUDAH</option><option>SEDANG</option><option>SULIT</option></select></label></div><label>Pembahasan<textarea name="explanation"/></label><button className="btn primary wide" disabled={busy}>Simpan soal</button></form></Panel><Panel eyebrow="HUBUNGKAN" title="Tambahkan ke tryout"><form className="dash-form" onSubmit={add}><label>Tryout<select name="examId" required onChange={e=>void loadItems(e.target.value)}><option value="">Pilih tryout</option>{exams.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Soal<select name="questionId" required><option value="">Pilih soal</option>{qs.map(q=><option key={q.id} value={q.id}>{q.subject} · {q.topic} · {String(q.question_text).slice(0,48)}</option>)}</select></label><label>Bobot poin<input name="points" type="number" min="1" defaultValue="1"/></label><button className="btn secondary wide" disabled={busy}>Tambahkan soal</button></form><div className="divider"/><div className="mini-list">{qs.slice(0,8).map(q=><div key={q.id}><span><b>{q.subject}</b><small>{q.topic}</small></span><Status value={q.difficulty}/></div>)}</div></Panel></div><Panel eyebrow="SUSUNAN TRYOUT" title={examId?`${items.length} soal terhubung`:"Pilih tryout di atas"}>{!examId?<Empty text="Pilih tryout untuk melihat susunan soal."/>:items.length===0?<Empty text="Tryout ini belum memiliki soal."/>:<div className="exam-item-list">{items.map((it,i)=><div key={it.id}><b>{i+1}</b><span><strong>{it.subject} · {it.topic}</strong><small>{it.question_text}</small></span><em>{it.points} poin</em><button onClick={()=>void remove(it.id)}>Hapus</button></div>)}</div>}</Panel></DashboardShell>
}
