"use client";
import {useEffect,useState} from "react";
import DashboardShell from "@/components/DashboardShell";
import {STUDENT_NAV} from "@/lib/dashboard-nav";
import {authedNalarva,formatDate,getStoredSession} from "@/lib/apps-script";
import {Empty,Loading,Status} from "@/components/dashboard/DashboardUI";
type Overview={progress:number;lastScore:number|null;rank:number|null;pendingAssignments:number;classes:number;upcomingSchedules:any[];recentMaterials:any[];access?:{active:boolean;endAt?:string;daysLeft?:number;packageName?:string}};
export default function Page(){
 const [data,setData]=useState<Overview|null>(null),[name,setName]=useState("Siswa Nalarva");useEffect(()=>{setName(getStoredSession()?.user?.name||"Siswa Nalarva");authedNalarva<Overview>("studentOverview").then(r=>setData(r.data||null))},[]);
 return <DashboardShell accessRole="SISWA" role="Siswa · TKA" name={name} initials="SN" nav={STUDENT_NAV}>
  <div className="dash-welcome"><div><small>Ruang Belajar</small><h1>Halo, {name.split(" ")[0]} 👋</h1><p>Lanjutkan target belajar dan pantau perkembangan dari data aktual akunmu.</p></div><a className="btn primary" href="/dashboard/siswa/materi">Lanjut Belajar</a></div>
  {!data?<Loading text="Memuat progres..."/>:<><div className={data.access?.active?"student-access-banner active":"student-access-banner expired"}><div><small>AKSES BELAJAR</small><b>{data.access?.active?`Aktif · ${data.access.packageName||"Paket Nalarva"}`:"Belum aktif / berakhir"}</b></div><div>{data.access?.active?<span>{data.access.daysLeft??0} hari tersisa</span>:<a href="/dashboard/siswa/langganan">Lihat langganan →</a>}</div></div><div className="stats"><div className="stat"><span>Progress tugas</span><b>{data.progress}%</b><small>Berdasarkan tugas yang dikumpulkan</small></div><div className="stat"><span>Tryout terakhir</span><b>{data.lastScore==null?"—":data.lastScore}</b><small>Skor terbaru</small></div><div className="stat"><span>Ranking</span><b>{data.rank?`#${data.rank}`:"—"}</b><small>Dari tryout terakhir</small></div><div className="stat"><span>Tugas pending</span><b>{data.pendingAssignments}</b><small>{data.classes} kelas aktif</small></div></div><div className="dash-grid"><section className="dash-card"><div className="card-head"><div><span>JADWAL</span><h3>Kelas berikutnya</h3></div></div>{data.upcomingSchedules.length?data.upcomingSchedules.map(s=><div className="schedule" key={s.id}><time>{formatDate(s.start_at,true)}</time><div><b>{s.title}</b><span>{s.class_name}</span></div><Status value={s.status}/></div>):<Empty text="Belum ada jadwal mendatang."/>}</section><section className="dash-card"><div className="card-head"><div><span>MATERI TERBARU</span><h3>Baru untukmu</h3></div></div>{data.recentMaterials.length?<div className="mini-list">{data.recentMaterials.map(m=><div key={m.id}><span><b>{m.title}</b><small>{m.class_name} · {formatDate(m.published_at)}</small></span><a href={m.drive_url||"#"} target="_blank" rel="noreferrer">Buka</a></div>)}</div>:<Empty text="Belum ada materi baru."/>}</section></div></>}
 </DashboardShell>
}
