"use client";
import {FormEvent,useEffect,useState} from "react";
import DashboardShell from "@/components/DashboardShell";
import {ADMIN_NAV} from "@/lib/dashboard-nav";
import {authedNalarva,formatDate} from "@/lib/apps-script";
import {Empty,Message,PageHead,Panel,Status} from "@/components/dashboard/DashboardUI";
type Row=Record<string,any>;
export default function Page(){
 const [rows,setRows]=useState<Row[]>([]),[programs,setPrograms]=useState<Row[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);async function load(){const [a,b]=await Promise.all([authedNalarva<Row[]>("listExams"),authedNalarva<Row[]>("listPrograms")]);setRows(a.data||[]);setPrograms(b.data||[])}useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);const r=await authedNalarva("adminCreateExam",Object.fromEntries(new FormData(form).entries()));setBusy(false);setMsg(r.message||"");if(r.ok){form.reset();await load()}}
 async function status(r:Row,next:string){const x=await authedNalarva("adminUpdateExamStatus",{examId:r.id,status:next});setMsg(x.message||"");if(x.ok)await load()}
 return <DashboardShell accessRole="ADMIN" role="Administrator" name="Admin Nalarva" initials="AD" nav={ADMIN_NAV}><PageHead eyebrow="Assessment" title="Tryout TKA" desc="Buat tryout, isi Bank Soal, lalu publikasikan ketika siap."/><div className="ops-grid"><Panel eyebrow="TRYOUT BARU" title="Buat tryout"><form className="dash-form" onSubmit={submit}><label>Program<select name="programId" required><option value="">Pilih program</option>{programs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="form-two"><label>Kode<input name="code" required placeholder="TO-SMA-01"/></label><label>Durasi (menit)<input name="durationMinutes" type="number" min="5" defaultValue="60"/></label></div><label>Judul<input name="title" required/></label><div className="form-two"><label>Mulai<input name="startAt" type="datetime-local"/></label><label>Selesai<input name="endAt" type="datetime-local"/></label></div><label>Status awal<select name="status"><option value="DRAFT">DRAFT</option><option value="PUBLISHED">PUBLISHED</option></select></label><button className="btn primary wide" disabled={busy}>Simpan tryout</button>{msg&&<Message text={msg}/>}</form></Panel><Panel eyebrow="TRYOUT" title={`${rows.length} tryout`}>{rows.length===0?<Empty/>:<div className="table-wrap"><table><thead><tr><th>Tryout</th><th>Program</th><th>Durasi</th><th>Soal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.title}</b><br/><small>{r.code}</small></td><td>{r.program_name||r.program_id}</td><td>{r.duration_minutes} mnt</td><td>{r.question_count||0}</td><td><Status value={r.status}/></td><td><div className="table-actions">{String(r.status)!=="PUBLISHED"?<button onClick={()=>void status(r,"PUBLISHED")}>Publikasikan</button>:<button onClick={()=>void status(r,"DRAFT")}>Jadikan draft</button>}<a href="/dashboard/admin/bank-soal">Kelola soal</a></div></td></tr>)}</tbody></table></div>}</Panel></div></DashboardShell>
}
